### ISSUE TITLE
stake_nmr should use api keys rather than password/mfa code

### ISSUE THREAD

**Issue by philipcmonk** [Omni-Analytics-Group/Rnumerai#1]
In `stake_nmr`, we require a password/mfa code because the endpoint looks like it requires them, but actually if you have a valid API token with permission to stake, then it doesn't check them.  I'll make those fields optional in the API at some point, but in the meantime, you can just fill in any value, like here: https://github.com/numerai/NumerAPI/pull/8/files#diff-a3450d33e802982f382963e711d2794eR438

**Comment by yogesh-bansal** [comment]
In the commit https://github.com/Omni-Analytics-Group/RnumeraiAPI/commit/88a21ad473e1a40d0850f312e48d587810198dad an empty string has been placed for password parameter as well, So the user is not required to enter his/her password.
