### ISSUE TITLE
errors with user_performance_data() & user_performance()

### ISSUE THREAD

**Issue by Shulgin-S** [Omni-Analytics-Group/Rnumerai#18]
failed to run user_performance_data(...) 
with 

> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
>   аргументы подразумевают разные количества строк: 1, 0

traced error back to this line.  

https://github.com/Omni-Analytics-Group/Rnumerai/blob/9bb22342c4ceb1c3b47a311b91967e6062f58bc1/R/source.R#L694

Probably some changes in results that return Numerai-API, as I See a lot of NULL values in "date" field. Need to check . Found that have to make  NULL check (just like in other fields)
`sapply(query_pass$data$v2UserProfile$dailySubmissionPerformances,  function(x) ifelse(is.null(x[["date"]]), NA, x[["date"]]))`

**Comment by erichare** [comment]
Thanks @Shulgin-S !! we've just fixed it in the `model_id_nulls` branch

**Comment by yogesh-bansal** [comment]
Fixed
