### ISSUE TITLE
Problem with  mulit-model set-up (get_models and submission)

### ISSUE THREAD

**Issue by rwarnung** [Omni-Analytics-Group/Rnumerai#19]
I face the following issue. I have three models set-up on my account. In the end of my pipeline the  call to `submit_predictions` returns an error and the call to `get_models` returns an empty list:

`get_models()`

> named list()

If I try to use the model id directly I get the following error on `submit_predictions`
```

submit_predictions( 
  pred_for_submission, 
  location = "./submissions_uploaded", tournament =  "kazutsugi",
  model_id = "xy-yxyx-yxyx-yxyx-yxyxyxyxxyx")
```

> Error in handle_url(handle, url, ...) : 
>   Must specify at least one of url or handle

Thanks a lot!

**Comment by Shulgin-S** [comment]
Also faced the same error: after some debuging found that at submit_predictions() you need treat model_id as character and escape it in query in two places at lines 271 & 289 (of current source.R)
```
271: modelId:\"',model_id,'\"){
289: modelId:\"',model_id,'\"){id}
```

**Comment by rwarnung** [comment]
The issue with `get_models` is easily resolved if one generates new API keys (this is after the transition ot the multi-model setting). `get_models` is fine as I see it.

**Comment by yogesh-bansal** [comment]
Made relevant changes to force pass the model id as a string.
