### ISSUE TITLE
Current round query could be simpler

### ISSUE THREAD

**Issue by philipcmonk** [Omni-Analytics-Group/Rnumerai#2]
It's undocumented but official that the `rounds` query with an argument of `0` gives you the current round.  Thus, `query {rounds(number: 0) {number}}` gives you the current round.

Currently, we only get the current round in the `stake_nmr` function, but arguably that should be a separate, public function as well.

**Comment by yogesh-bansal** [comment]
In commit https://github.com/Omni-Analytics-Group/RnumeraiAPI/commit/88a21ad473e1a40d0850f312e48d587810198dad Added a `current_round()` function to the package which fetches the current round information based on `number:0` argument as suggested above. `stake_nmr()` function now uses the `current_round()` function to get the latest round number.
