### ISSUE TITLE
Errors with performance_over_time() and user_performance() 

### ISSUE THREAD

**Issue by woobe** [Omni-Analytics-Group/Rnumerai#20]
For example, when I try `performance_over_time("ia_ai", "Round_Correlation")`, it returns
`Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, :
arguments imply differing number of rows: 0, 1`.

ssh had problems with `user_performance()` and found that the error is due to `NULL` values in some field (e.g. RANK). 

Here is ssh's local fix:

`user_performance <- data.frame(
    Date = sapply(query_pass$data$v2UserProfile$dailyUserPerformances, function(x) ifelse(is.null(x[["date"]]), NA, x[["date"]]) ), 
    Tier = sapply(query_pass$data$v2UserProfile$dailyUserPerformances, function(x) ifelse(is.null(x[["tier"]]), NA, x[["tier"]]) ), 
    Reputation = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,  function(x) ifelse(is.null(x[["reputation"]]), NA, x[["reputation"]]) ), 
    Rank = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,  function(x) ifelse(is.null(x[["rank"]]), NA, x[["rank"]]) ), 
     NMR_Staked = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,  function(x) ifelse(is.null(x[["stakeValue"]]), NA, x[["stakeValue"]])),
    Leaderboard_Bonus = sapply(query_pass$data$v2UserProfile$dailyUserPerformances, function(x) ifelse(is.null(x[["leaderboardBonus"]]), NA, x[["leaderboardBonus"]])), 
    Payout_NMR = sapply(query_pass$data$v2UserProfile$dailyUserPerformances, 
                                                   function(x) ifelse(is.null(x[["averageCorrelationPayout"]]), 
                                                                      NA, x[["averageCorrelationPayout"]])), 
    Average_Daily_Correlation = sapply(query_pass$data$v2UserProfile$dailyUserPerformances, 
                                                                  function(x) ifelse(is.null(x[["averageCorrelation"]]), 
                                                                                     NA, x[["averageCorrelation"]])) )`

(sorry for the poor code formatting)

**Comment by Shulgin-S** [comment]
as @woobe  described for me helped to 
update lines 691-694
https://github.com/Omni-Analytics-Group/Rnumerai/blob/166bb095063fa6438afceabcba6cabf528e41411/R/source.R#L694

```
Date = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,"[[","date"),
Tier = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,"[[","tier"),
Reputation = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,"[[","reputation"),
Rank = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,"[[","rank"),
```

into something like in next lines 
https://github.com/Omni-Analytics-Group/Rnumerai/blob/166bb095063fa6438afceabcba6cabf528e41411/R/source.R#L695

my local fix that helped:
```
Date = sapply(query_pass$data$v2UserProfile$dailyUserPerformances, function(x) ifelse(is.null(x[["date"]]), NA, x[["date"]]) ), 
Tier = sapply(query_pass$data$v2UserProfile$dailyUserPerformances, function(x) ifelse(is.null(x[["tier"]]), NA, x[["tier"]]) ), 
Reputation = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,  function(x) ifelse(is.null(x[["reputation"]]), NA, x[["reputation"]]) ), 
Rank = sapply(query_pass$data$v2UserProfile$dailyUserPerformances,  function(x) ifelse(is.null(x[["rank"]]), NA, x[["rank"]]) ), 

```                                 

with check for NULL value. As far as I remember it was only one field (Rank) but as it's not the first time that API starts to return NULL, maybe it's a good approach to check all others 3 fields (Date, Tier, Reputation) withing this dataframe transformation.
