### ISSUE TITLE
illegal model_id when submit_predictions

### ISSUE THREAD

**Issue by completelyAbsorbed** [Omni-Analytics-Group/Rnumerai#24]
hello, I am able to successfully authenticate with my API key and public ID, download data, then when I try to submit_predictions() I get this: 

Error in submit_predictions(submission = submission_, model_id = model_ID,  : 
  illegal: ",modelId:<redacted>){id}

<redacted> is a stand-in for my model uuid, as copied from https://numer.ai/models and declared in the R script (fast fixes, I am aware of this being a bad practice)

here are some calls that might be useful

 > class(submission_)
[1] "data.frame"
> class(data_dir)
[1] "character"
> class(model_ID)
[1] "character"

> dim(submission_)
[1] 1601973       2

made a csv from submission_ and submitted manually. not sure what's wrong here.

thanks!

**Comment by completelyAbsorbed** [comment]
following up, I replaced the public ID (same value) and secret key (different value) with those from numer.ai/submit and now getting this error (new model id... i enabled multi model support after the last post)

> submission_id <- submit_predictions(submission = submission_,
+                                     model_id = model_ID,
+                                     location = data_dir)
Error in handle_url(handle, url, ...) : 
  Must specify at least one of url or handle

**Comment by completelyAbsorbed** [comment]
tried again this week, same issue getting error in handle_url when submit_predictions.

**Comment by rwarnung** [comment]
@completelyAbsorbed do you use the CRAN version or the current dev from GitHub? I adapted the package to the nomi target. It just works in my branch and I assume it works on the dev version here too as they accept my PR.

**Comment by completelyAbsorbed** [comment]
thanks, I use the CRAN version, but will test the dev version later today. fingers crossed :) will update after

**Comment by completelyAbsorbed** [comment]
works with dev version. doesn't work for me with CRAN version. cheers (closing this)
