### ISSUE TITLE
Submission method does not handle upload errors

### ISSUE THREAD

**Issue by kumikoda** [Omni-Analytics-Group/Rnumerai#26]
## Problem
https://github.com/Omni-Analytics-Group/Rnumerai/blob/e7b6ea090b57c9d03bce566fc9ff51013603f882/R/source.R#L279

![image](https://user-images.githubusercontent.com/1307362/103186213-86ce3800-4874-11eb-93f3-d123eec969d7.png)

This step can fail if/when a user's internet provider is blocking file uploads to AWS S3. This could result in a timeout or 4XX. Currently the code will just succeed, ie `mysubmission` is never checked nor used.

When it gets to the step where you register the submission with the API, the user will end up with the error "submission file not found, was it uploaded correctly?"

## Expectation
Users should be notified of any HTTP errors in the entire flow of uploading 

## Solution?
Check for HTTP errors like this :)
https://campus.datacamp.com/courses/working-with-web-data-in-r/using-httr-to-interact-with-apis-directly?ex=7

**Comment by erichare** [comment]
@kumikoda very good point. Do you know what the expected return is from the PUT? HTTP 200, HTTP 201? Right now i have a patch like this: https://github.com/Omni-Analytics-Group/Rnumerai/pull/27 but maybe it can be refined.

**Comment by LiamHz** [comment]
Hi Eric! I work at Numerai and @kumikoda asked me to look into this and respond for him

The expected return from our api for submissions is HTTP 200. Your PR looks fine as is, but if you want, we could remove ` && mysubmission$status_code != 201` from the conditional

**Comment by erichare** [comment]
Thank you @LiamHz ! I've made the change and merged in the PR. Appreciate the help!
