### ISSUE TITLE
Feature Request: Trigger ID Handling

### ISSUE THREAD

**Issue by ndharasz** [Omni-Analytics-Group/Rnumerai#28]
The Numerai GraphQL API now accepts an optional, nullable field "triggerId" on the `createSubmission` mutation. For those using Numerai Compute 0.3.0 (coming soon) to automate submissions, this triggerId is set as an environment variable name "TRIGGER_ID" when their Prediction Nodes are triggered by Numerai.

I'd like rlang users to start passing this triggerId passively when submitting with Rnumerai.
For reference, here is the python numerapi change to get "TRIGGER_ID" from the environment variables, defaulting to null, and pass it to `createSubmission`:

https://github.com/uuazed/numerapi/commit/954576ffcfdc322039d36fa5a6ec751d3210848f#diff-86e196617613d3be89e0e86d0d74037d24ef8ced8d631d51b6201dc211f9b3f5L761-L775

**Comment by erichare** [comment]
Hi @ndharasz , I opened a PR which should supply the optional `triggerId` field in createSubmission. Could you, or anyone you know who uses Rnumerai, possibly help by testing it? You can install the branch with:

`devtools::install_github("Omni-Analytics-Group/Rnumerai", ref="signals")`

**Comment by ndharasz** [comment]
Yep, I'll make sure this gets tested and will get back to you with the results. Thanks for handling this :)

**Comment by yogesh-bansal** [comment]
Fixed in latest commits.
