### ISSUE TITLE
Submit predictions for Signals Tournament using Rnumerai?

### ISSUE THREAD

**Issue by aqsmith08** [Omni-Analytics-Group/Rnumerai#31]
Hi Omni,

Thanks for creating the Rnumerai package. With the start of [Numerai Signals Tournament](https://signals.numer.ai/tournament), I was wondering if the `submit_predictions` function in this package would be good home to submit predictions for that tournament? I'm looking for a way to automate submissions utilizing R and thought this might be the best option at first glance. If not, I'll continue to poke around. Thanks!

**Comment by yogesh-bansal** [comment]
Yeah, You can submit predictions to the main tournament using
`submit_predictions(submission,data_dir,tournament="Nomi")`
and can submit the signals submission using 
`submit_predictions(submission,data_dir,tournament="Signals")`
using the same `submit_predictions` function of this package.

Just make sure to install the latest version of this package using
`devtools::install_github("Omni-Analytics-Group/Rnumerai")`

**Comment by aqsmith08** [comment]
Ah, very cool. I hadn't seen that update in the PDF. I'll install the latest version and use that. Thanks for your quick response!
