### ISSUE TITLE
run_query(...): Remove Content-Type and Accept from add_headers(...)

### ISSUE THREAD

**Issue by OVVO-Financial** [Omni-Analytics-Group/Rnumerai#33]
```
raw <- POST(
  url = "https://api-tournament.numer.ai",
  body = list(query = query),
  encode = "json",
  add_headers(Authorization = paste0("Token ", id, "$", key))
  )
```

I can confirm the changes work locally but not sure if this is best solution...

**Comment by Shulgin-S** [comment]
I did round 274 submissions with this local alteration to Rnumerai::run_query(). Still hope they will fix the problem with "Content-Type" field in a header on the API server-side.

**Comment by yogesh-bansal** [comment]
Merged the fix proposed
