### ISSUE TITLE
Include "source" during submissions

### ISSUE THREAD

**Issue by ndharasz** [Omni-Analytics-Group/Rnumerai#37]
Numerai added a new, optional `source` field to createSubmission and createSignalsSubmission GraphQL Mutations. Please send `source: 'rnumerai'` when creating submissions for Numerai tournament and signals. There is a 1 NMR bounty available when complete.

**Comment by OVVO-Financial** [comment]
Completed, update noted in EDIT #2.

https://github.com/Omni-Analytics-Group/Rnumerai/issues/36#issue-993987004

**Comment by OVVO-Financial** [comment]
Merged...

**Comment by erichare** [comment]
Closing as this is now on CRAN. Thanks!
