### ISSUE TITLE
round_stats(  ) does not work anymore since round 99

### ISSUE THREAD

**Issue by rwarnung** [Omni-Analytics-Group/Rnumerai#5]
Hi, thanks for the great package that saves me a lot of time.
I just noticed that `round_stats `does not work for arguments greater 98.

`round_stats( 98)`

gives the leaderboard information and 

`round_stats( 99)`

gives the error:

> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
>   arguments imply differing number of rows: 1, 0

**Comment by yogesh-bansal** [comment]
We are looking into it and provide the fix earliest.

**Comment by yogesh-bansal** [comment]
Please make sure you have the latest version of the Rnumerai package.
To install the latest version use
`devtools::install_github("Omni-Analytics-Group/Rnumerai")`

**Comment by rwarnung** [comment]
@yogesh-bansal thank you! the version from github works. With current CRAN version it seems to work for the running round (102) but not 101 or 100.

**Comment by yogesh-bansal** [comment]
Yeah, The due to the recent changes with numerai.ai the development works, The CRAN package would with be updated with the recent changes pretty soon. 
Closing the issue for now.
