### ISSUE TITLE
New tournament format and data download

### ISSUE THREAD

**Issue by rwarnung** [Omni-Analytics-Group/Rnumerai#6]
Hi,
I am a happy user of your useful package. However, numer.ai has changed the tournament design. Now predictions are done for 5 different targets (one by one). 
When I participated last time, I experienced that the upload of submissions went to the "Bernie" tournament. I wonder if you plan to add the functionality to submit to the various tournaments.

On the other hand, the download of data seems not to work at the moment.
the call

`download_data(data_dir)`

gives the error

>  Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
>   Failed to open file C:\xxxx\numerai_dataset_2018-06-15.zip. 

It is interesting that it puts today's date 2018-06-15 in the message as the round has started some days ago.
Do you need any additional information?
Thank you and kind regards,
Richard

**Comment by yogesh-bansal** [comment]
Hi,
Multiple tournament support has been added, Try installing the latest version using 
`devtools::install_github("Omni-Analytics-Group/Rnumerai")`

Check out the Readme for new tournament name parameter support.
Let us know if you find any issues with the package.

**Comment by rwarnung** [comment]
Thank you for your work @yogesh-bansal 
The download works fine!
For the upload of submissions: I can set the parameter `tournament`
But a call of the form 

`submit_predictions( pred_for_submission,  tournament = "Bernie")`

gives 

> Submitted Prediction with id 
> NULL

Could it be that there still is a problem? 
The submission does not work for solutions that I can upload manually. Thus there format should be ok.

Thank you!

**Comment by rwarnung** [comment]
Staking per tournament works! It is just the submission/upload that seems not to work.
Thank you! @yogesh-bansal

**Comment by yogesh-bansal** [comment]
Can you post the output for the object `head(pred_for_submission)`?

**Comment by yogesh-bansal** [comment]
Try installing the latest version using
`devtools::install_github("Omni-Analytics-Group/Rnumerai")`

We have added error reporting in submission function, So you should receive the error message stating why the upload attempt returned a submission_id.

Let us know, If you are still facing any issues with the package, We would be happy to resolve that asap.

Regards

**Comment by rwarnung** [comment]
Hi, 
Thank you for working on this!
I have uploaded and staked all my models so for now I can not upload again.
To address your first idea I post head of my submission:

`head(sol)`

gives

> # A tibble: 6 x 2
>   id               probability_elizabeth
>   <chr>                            <dbl>
> 1 n60dffdaceb7e467                 0.4xx
> 2 nadaeef0214b84a8                 0.5xx
> 3 nb13883520a4344f                 0.4xx
> 4 n423766c5a4fa42a                 0.4xx
> 5 n75a5baf93a624cc                 0.4xx
> 6 n2ff91086716e413                 0.5xx

Thus the probability column needs to have the tournament name in **lower case** in the columnname.
In this case it is "probability_elizabeth" with lower case for "elizabeth". The data typ for the ids is `<chr>` and it is `<dbl>`  for the column "probability_elizabeth".

Kind regards!

**Comment by yogesh-bansal** [comment]
Thanks.
So the issue here was that you need not to manually put the tournament name in probability column, You just have two columns id and probability, and the tournament name would be appended to probability column based on the `tournament` parameter in function `submit_predictions`.
Now we have added the error reporting for same as well.

Regards

**Comment by rwarnung** [comment]
@yogesh-bansal thank you! This is an extra service. I coded the renaming of the column. Now I will revert the code and it will be fine. Thank you!

**Comment by rwarnung** [comment]
@yogesh-bansal thank you for your work! The submission of solutions worked perfectly!
