### ISSUE TITLE
The upload does not work due to new tournament names

### ISSUE THREAD

**Issue by rwarnung** [Omni-Analytics-Group/Rnumerai#8]
Hi, there are two new tournaments available: "Hillary" and "Frank".
The function `submit_predictions` checks for the old names and does not accept the new ones.
The error message is

> Parsed with column specification:
> cols(
>   id = col_character(),
>   probability = col_double()
> )
> Error in submit_predictions(pred_for_submission %>% change_probname, tournament = tour_string) : 
>   Tournament Name doesn't match

Could you add the new names to the list or for future chnages take out this check? Thank you!

**Comment by rwarnung** [comment]
The same issue comes up with the function `round_stats`. Maybe it would really be a good idea to just take out the check for a given list of tournament names. This would make the package fit for future changes.

**Comment by rwarnung** [comment]
Same problem with `stake_nmr_multi`

**Comment by yogesh-bansal** [comment]
Code fixed with the latest commit.
Install the latest version using `devtools::install_github("Omni-Analytics-Group/Rnumerai")`
